package com.eazpire.creator.ui.account

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Image
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage
import com.eazpire.creator.EazColors
import com.eazpire.creator.auth.SecureTokenStore
import com.eazpire.creator.i18n.LocalTranslationStore
import com.eazpire.creator.mockup.CustomerMockPreviewStore
import com.eazpire.creator.ui.components.HangerIcon
import com.eazpire.creator.util.DebugLog
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import org.json.JSONArray

/**
 * My Mockups — aligned with web [my-mockups.js]:
 * photo library, per-product generate, Wearing toggle, shared backend ops.
 */
data class MockupProfilePhoto(
    val id: Long,
    val url: String,
    val personType: String?
)

data class MockupCatalogProduct(
    val productKey: String,
    val productName: String,
    val mockupUrl: String?,
    val templateUrl: String?,
    val activeMockupId: Long?,
    val useAsPreview: Boolean,
    val isGenerated: Boolean,
    val status: String?
)

@Composable
fun AccountMockupsTab(
    tokenStore: SecureTokenStore,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val store = LocalTranslationStore.current
    val t = store?.let { { k: String, d: String -> it.t(k, d) } } ?: { _: String, d: String -> d }
    val jwt = remember { runCatching { tokenStore.getJwt() }.getOrNull() }
    val ownerId = remember { runCatching { tokenStore.getOwnerId() }.getOrNull() ?: "" }

    var photos by remember { mutableStateOf<List<MockupProfilePhoto>>(emptyList()) }
    var generated by remember { mutableStateOf<List<MockupCatalogProduct>>(emptyList()) }
    var available by remember { mutableStateOf<List<MockupCatalogProduct>>(emptyList()) }
    var isLoading by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf<String?>(null) }
    var uploadPersonType by remember { mutableStateOf("woman") }
    var isGenerating by remember { mutableStateOf(false) }
    var generatingProgress by remember { mutableStateOf("") }
    var lightboxProduct by remember { mutableStateOf<MockupCatalogProduct?>(null) }
    var deleteConfirm by remember { mutableStateOf<MockupCatalogProduct?>(null) }

    val api = remember(jwt) { com.eazpire.creator.api.CreatorApi(jwt = jwt) }
    val scope = rememberCoroutineScope()

    val photoPicker = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        if (uri == null || ownerId.isBlank()) return@rememberLauncherForActivityResult
        scope.launch {
            isGenerating = true
            generatingProgress = t("creator.my_mockups.uploading", "Uploading photo…")
            errorMessage = null
            try {
                val bytes = context.contentResolver.openInputStream(uri)?.use { it.readBytes() }
                    ?: throw IllegalArgumentException("Could not read photo")
                val contentType = context.contentResolver.getType(uri) ?: "image/jpeg"
                val resp = api.uploadMockupPhoto(ownerId, bytes, contentType, uploadPersonType)
                if (!resp.optBoolean("ok", false)) {
                    errorMessage = resp.optString("error", "Upload failed")
                } else {
                    reloadCatalog(api, ownerId) { p, g, a ->
                        photos = p
                        generated = g
                        available = a
                    }
                }
            } catch (e: Exception) {
                DebugLog.click("Mockup upload error: ${e.message}")
                errorMessage = e.message ?: "Upload failed"
            } finally {
                isGenerating = false
            }
        }
    }

    fun reload() {
        scope.launch {
            if (ownerId.isBlank()) return@launch
            isLoading = true
            errorMessage = null
            try {
                reloadCatalog(api, ownerId) { p, g, a ->
                    photos = p
                    generated = g
                    available = a
                }
            } catch (e: Exception) {
                errorMessage = e.message ?: "Failed to load"
            } finally {
                isLoading = false
            }
        }
    }

    LaunchedEffect(ownerId) {
        if (ownerId.isBlank()) return@LaunchedEffect
        isLoading = true
        try {
            reloadCatalog(api, ownerId) { p, g, a ->
                photos = p
                generated = g
                available = a
            }
        } catch (e: Exception) {
            errorMessage = e.message
        } finally {
            isLoading = false
        }
    }

    fun onGenerateProduct(product: MockupCatalogProduct) {
        if (ownerId.isBlank() || photos.isEmpty()) {
            errorMessage = t("creator.my_mockups.need_photo", "Upload a profile photo first.")
            return
        }
        isGenerating = true
        generatingProgress = t("creator.my_mockups.generating", "Generating…")
        scope.launch {
            try {
                val photoIds = photos.map { it.id }
                val resp = api.generateCustomerMockupsForProduct(ownerId, product.productKey, photoIds)
                if (!resp.optBoolean("ok", false)) {
                    errorMessage = resp.optString("error", "Generation failed")
                    return@launch
                }
                val jobId = resp.optString("job_id", "")
                val total = resp.optInt("total_products", photoIds.size).coerceAtLeast(1)
                var done = false
                while (!done) {
                    delay(3000)
                    val poll = api.pollJob(jobId)
                    val completed = poll.optInt("completed_products", 0)
                    generatingProgress = "$completed / $total"
                    done = poll.optBoolean("done", false)
                }
                CustomerMockPreviewStore.invalidate()
                reloadCatalog(api, ownerId) { p, g, a ->
                    photos = p
                    generated = g
                    available = a
                }
            } catch (e: Exception) {
                errorMessage = e.message ?: "Generation failed"
            } finally {
                isGenerating = false
            }
        }
    }

    fun onToggleWearing(product: MockupCatalogProduct) {
        val mockupId = product.activeMockupId ?: return
        scope.launch {
            try {
                val resp = api.toggleMockupPreview(ownerId, mockupId, !product.useAsPreview)
                if (resp.optBoolean("ok", false)) {
                    CustomerMockPreviewStore.invalidate()
                    reload()
                }
            } catch (_: Exception) { }
        }
    }

    fun onDelete(product: MockupCatalogProduct) {
        val mockupId = product.activeMockupId ?: return
        deleteConfirm = null
        lightboxProduct = null
        scope.launch {
            try {
                val resp = api.deleteCustomerMockup(ownerId, mockupId)
                if (resp.optBoolean("ok", false)) {
                    CustomerMockPreviewStore.invalidate()
                    reload()
                } else {
                    errorMessage = resp.optString("error", "Delete failed")
                }
            } catch (e: Exception) {
                errorMessage = e.message
            }
        }
    }

    Column(
        modifier = modifier
            .fillMaxWidth()
            .verticalScroll(rememberScrollState())
            .padding(8.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = t("creator.my_mockups.title", "My Mockups"),
            style = MaterialTheme.typography.titleMedium,
            color = EazColors.TextPrimary
        )
        Text(
            text = t(
                "creator.my_mockups.subtitle",
                "Upload photos, generate mocks per product, and set Wearing for shop preview."
            ),
            style = MaterialTheme.typography.bodySmall,
            color = EazColors.TextSecondary
        )

        if (ownerId.isBlank()) {
            Text(
                t("creator.my_mockups.login_required", "Please log in to use My Mockups."),
                color = EazColors.TextSecondary
            )
            return@Column
        }

        if (isGenerating) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                CircularProgressIndicator(modifier = Modifier.size(24.dp), color = EazColors.Orange)
                Spacer(Modifier.width(12.dp))
                Text(generatingProgress, style = MaterialTheme.typography.bodySmall)
            }
        }

        errorMessage?.let {
            Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
        }

        Text(t("creator.my_mockups.photos", "Profile photos"), style = MaterialTheme.typography.labelLarge)
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .horizontalScroll(rememberScrollState()),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            photos.forEach { photo ->
                Box(
                    modifier = Modifier
                        .size(72.dp)
                        .clip(RoundedCornerShape(8.dp))
                ) {
                    AsyncImage(
                        model = photo.url,
                        contentDescription = null,
                        modifier = Modifier.fillMaxSize(),
                        contentScale = ContentScale.Crop
                    )
                }
            }
            OutlinedButton(onClick = { photoPicker.launch("image/*") }) {
                Icon(Icons.Default.Add, contentDescription = null, modifier = Modifier.size(18.dp))
                Spacer(Modifier.width(4.dp))
                Text(t("creator.my_mockups.add_photo", "Add photo"))
            }
        }

        if (isLoading) {
            CircularProgressIndicator(color = EazColors.Orange, modifier = Modifier.padding(24.dp))
        } else {
            if (generated.isNotEmpty()) {
                Text(
                    t("creator.my_mockups.generated", "My mocks"),
                    style = MaterialTheme.typography.labelLarge,
                    modifier = Modifier.padding(top = 8.dp)
                )
                MockupProductGrid(
                    products = generated,
                    t = t,
                    onOpen = { lightboxProduct = it },
                    onToggleWearing = { onToggleWearing(it) },
                    onDelete = { deleteConfirm = it }
                )
            }
            if (available.isNotEmpty()) {
                Text(
                    t("creator.my_mockups.available", "Available products"),
                    style = MaterialTheme.typography.labelLarge,
                    modifier = Modifier.padding(top = 8.dp)
                )
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    available.forEach { product ->
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
                        ) {
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(8.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                AsyncImage(
                                    model = product.templateUrl ?: product.mockupUrl,
                                    contentDescription = null,
                                    modifier = Modifier
                                        .size(56.dp)
                                        .clip(RoundedCornerShape(8.dp)),
                                    contentScale = ContentScale.Crop
                                )
                                Column(modifier = Modifier.weight(1f).padding(horizontal = 8.dp)) {
                                    Text(
                                        product.productName,
                                        style = MaterialTheme.typography.bodySmall,
                                        maxLines = 2
                                    )
                                }
                                Button(
                                    onClick = { onGenerateProduct(product) },
                                    enabled = !isGenerating && photos.isNotEmpty()
                                ) {
                                    Text(t("creator.my_mockups.generate", "Generate"))
                                }
                            }
                        }
                    }
                }
            }
            if (generated.isEmpty() && available.isEmpty()) {
                Text(
                    t("creator.my_mockups.empty", "No products in catalog."),
                    color = EazColors.TextSecondary
                )
            }
        }
    }

    lightboxProduct?.let { product ->
        AlertDialog(
            onDismissRequest = { lightboxProduct = null },
            title = { Text(product.productName) },
            text = {
                val url = product.mockupUrl ?: product.templateUrl
                if (!url.isNullOrBlank()) {
                    AsyncImage(
                        model = url,
                        contentDescription = null,
                        modifier = Modifier
                            .fillMaxWidth()
                            .aspectRatio(1f)
                            .clip(RoundedCornerShape(8.dp))
                    )
                }
            },
            confirmButton = {
                TextButton(onClick = { lightboxProduct = null }) {
                    Text(t("creator.common.close", "Close"))
                }
            }
        )
    }

    deleteConfirm?.let { product ->
        AlertDialog(
            onDismissRequest = { deleteConfirm = null },
            title = { Text(t("creator.my_mockups.delete_title", "Delete mockup?")) },
            text = { Text(t("creator.my_mockups.delete_body", "This mockup will be permanently deleted.")) },
            confirmButton = {
                TextButton(onClick = { onDelete(product) }) {
                    Text(t("creator.common.delete", "Delete"), color = MaterialTheme.colorScheme.error)
                }
            },
            dismissButton = {
                TextButton(onClick = { deleteConfirm = null }) {
                    Text(t("creator.common.cancel", "Cancel"))
                }
            }
        )
    }
}

@Composable
private fun MockupProductGrid(
    products: List<MockupCatalogProduct>,
    t: (String, String) -> String,
    onOpen: (MockupCatalogProduct) -> Unit,
    onToggleWearing: (MockupCatalogProduct) -> Unit,
    onDelete: (MockupCatalogProduct) -> Unit
) {
    products.chunked(2).forEach { row ->
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            row.forEach { product ->
                Card(
                    modifier = Modifier
                        .weight(1f)
                        .aspectRatio(0.85f)
                        .clickable { onOpen(product) },
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column {
                        Box(modifier = Modifier.weight(1f).fillMaxWidth()) {
                            val url = product.mockupUrl ?: product.templateUrl
                            if (!url.isNullOrBlank()) {
                                AsyncImage(
                                    model = url,
                                    contentDescription = null,
                                    modifier = Modifier.fillMaxSize(),
                                    contentScale = ContentScale.Crop
                                )
                            } else {
                                Box(
                                    Modifier
                                        .fillMaxSize()
                                        .background(EazColors.TopbarBorder.copy(alpha = 0.3f)),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Icon(Icons.Default.Image, null, tint = EazColors.TextSecondary)
                                }
                            }
                        }
                        Row(
                            modifier = Modifier.fillMaxWidth().padding(6.dp),
                            horizontalArrangement = Arrangement.End
                        ) {
                            IconButton(onClick = { onDelete(product) }, modifier = Modifier.size(32.dp)) {
                                Icon(Icons.Default.Delete, null, modifier = Modifier.size(16.dp))
                            }
                            IconButton(
                                onClick = { onToggleWearing(product) },
                                modifier = Modifier
                                    .size(32.dp)
                                    .background(
                                        if (product.useAsPreview) Color(0xFF111827) else Color(0xFFF9FAFB),
                                        RoundedCornerShape(8.dp)
                                    )
                            ) {
                                HangerIcon(
                                    color = if (product.useAsPreview) Color.White else Color(0xFF374151),
                                    size = 16.dp
                                )
                            }
                        }
                    }
                }
            }
            if (row.size == 1) Spacer(Modifier.weight(1f))
        }
    }
}

private suspend fun reloadCatalog(
    api: com.eazpire.creator.api.CreatorApi,
    ownerId: String,
    onResult: (List<MockupProfilePhoto>, List<MockupCatalogProduct>, List<MockupCatalogProduct>) -> Unit
) {
    val photosResp = api.listMockupPhotos(ownerId)
    val photos = if (photosResp.optBoolean("ok", false)) {
        parsePhotos(photosResp.optJSONArray("photos"))
    } else emptyList()

    val prodResp = api.listMockupProducts(ownerId)
    val generated = mutableListOf<MockupCatalogProduct>()
    val available = mutableListOf<MockupCatalogProduct>()
    if (prodResp.optBoolean("ok", false)) {
        parseCatalogProducts(prodResp.optJSONArray("generated"), true, generated)
        parseCatalogProducts(prodResp.optJSONArray("available"), false, available)
    }
    onResult(photos, generated, available)
}

private fun parsePhotos(arr: JSONArray?): List<MockupProfilePhoto> {
    if (arr == null) return emptyList()
    return (0 until arr.length()).mapNotNull { i ->
        val o = arr.optJSONObject(i) ?: return@mapNotNull null
        val id = o.optLong("id", -1L)
        if (id < 0) return@mapNotNull null
        MockupProfilePhoto(
            id = id,
            url = o.optString("url", ""),
            personType = o.optString("person_type").takeIf { it.isNotBlank() }
        )
    }
}

private fun parseCatalogProducts(
    arr: JSONArray?,
    isGenerated: Boolean,
    out: MutableList<MockupCatalogProduct>
) {
    if (arr == null) return
    for (i in 0 until arr.length()) {
        val o = arr.optJSONObject(i) ?: continue
        val pk = o.optString("product_key", "")
        if (pk.isBlank()) continue
        out.add(
            MockupCatalogProduct(
                productKey = pk,
                productName = o.optString("product_name", pk),
                mockupUrl = o.optString("mockup_url").takeIf { it.isNotBlank() },
                templateUrl = o.optString("template_url").takeIf { it.isNotBlank() },
                activeMockupId = o.optLong("active_mockup_id", -1L).takeIf { it > 0 },
                useAsPreview = o.optBoolean("use_as_preview", false),
                isGenerated = isGenerated,
                status = o.optString("status").takeIf { it.isNotBlank() }
            )
        )
    }
}
