package com.eazpire.creator.ui.account

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.ChevronLeft
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Image
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage
import com.eazpire.creator.EazColors
import com.eazpire.creator.auth.SecureTokenStore
import com.eazpire.creator.i18n.LocalTranslationStore
import com.eazpire.creator.mockup.CustomerMockPreviewStore
import com.eazpire.creator.mockup.MockupPreviewPool
import com.eazpire.creator.ui.components.HangerIcon
import com.eazpire.creator.util.DebugLog
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import org.json.JSONArray

/**
 * My Mockups — aligned with web [my-mockups.js]:
 * photo library, per-product generate, Wearing toggle, shared backend ops.
 */
data class MockupProfilePhoto(
    val id: Long,
    val url: String,
    val personType: String?
)

data class MockupVariant(
    val id: Long,
    val mockupUrl: String?,
    val useAsPreview: Boolean
)

data class MockupCatalogProduct(
    val productKey: String,
    val productName: String,
    val mockupUrl: String?,
    val templateUrl: String?,
    val activeMockupId: Long?,
    val previewCount: Int,
    val shopPreviewEnabled: Boolean,
    val isGenerated: Boolean,
    val status: String?,
    val variants: List<MockupVariant> = emptyList()
) {
    val shopPreviewActive: Boolean get() = shopPreviewEnabled
}

@Composable
fun AccountMockupsTab(
    tokenStore: SecureTokenStore,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val store = LocalTranslationStore.current
    val t = store?.let { { k: String, d: String -> it.t(k, d) } } ?: { _: String, d: String -> d }
    val jwt = remember { runCatching { tokenStore.getJwt() }.getOrNull() }
    val ownerId = remember { runCatching { tokenStore.getOwnerId() }.getOrNull() ?: "" }

    var photos by remember { mutableStateOf<List<MockupProfilePhoto>>(emptyList()) }
    var generated by remember { mutableStateOf<List<MockupCatalogProduct>>(emptyList()) }
    var available by remember { mutableStateOf<List<MockupCatalogProduct>>(emptyList()) }
    var isLoading by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf<String?>(null) }
    var uploadPersonType by remember { mutableStateOf("woman") }
    var isGenerating by remember { mutableStateOf(false) }
    var generatingProgress by remember { mutableStateOf("") }
    var lightboxProduct by remember { mutableStateOf<MockupCatalogProduct?>(null) }
    var lightboxVariants by remember { mutableStateOf<List<MockupVariant>>(emptyList()) }
    var lightboxIndex by remember { mutableStateOf(0) }
    var deleteConfirm by remember { mutableStateOf<MockupCatalogProduct?>(null) }
    var autoMockEnabled by remember { mutableStateOf(true) }
    var wearingMockCount by remember { mutableIntStateOf(0) }

    val api = remember(jwt) { com.eazpire.creator.api.CreatorApi(jwt = jwt) }
    val scope = rememberCoroutineScope()

    val photoPicker = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        if (uri == null || ownerId.isBlank()) return@rememberLauncherForActivityResult
        scope.launch {
            isGenerating = true
            generatingProgress = t("creator.my_mockups.uploading", "Uploading photo…")
            errorMessage = null
            try {
                val bytes = context.contentResolver.openInputStream(uri)?.use { it.readBytes() }
                    ?: throw IllegalArgumentException("Could not read photo")
                val contentType = context.contentResolver.getType(uri) ?: "image/jpeg"
                val resp = api.uploadMockupPhoto(ownerId, bytes, contentType, uploadPersonType)
                if (!resp.optBoolean("ok", false)) {
                    errorMessage = resp.optString("error", "Upload failed")
                } else {
                    reloadCatalog(api, ownerId) { p, g, a, auto, count ->
                        photos = p
                        generated = g
                        available = a
                        autoMockEnabled = auto
                        wearingMockCount = count
                    }
                }
            } catch (e: Exception) {
                DebugLog.click("Mockup upload error: ${e.message}")
                errorMessage = e.message ?: "Upload failed"
            } finally {
                isGenerating = false
            }
        }
    }

    fun reload() {
        scope.launch {
            if (ownerId.isBlank()) return@launch
            isLoading = true
            errorMessage = null
            try {
                reloadCatalog(api, ownerId) { p, g, a, auto, count ->
                    photos = p
                    generated = g
                    available = a
                    autoMockEnabled = auto
                    wearingMockCount = count
                }
            } catch (e: Exception) {
                errorMessage = e.message ?: "Failed to load"
            } finally {
                isLoading = false
            }
        }
    }

    LaunchedEffect(ownerId) {
        if (ownerId.isBlank()) return@LaunchedEffect
        isLoading = true
        try {
            reloadCatalog(api, ownerId) { p, g, a, auto, count ->
                photos = p
                generated = g
                available = a
                autoMockEnabled = auto
                wearingMockCount = count
            }
        } catch (e: Exception) {
            errorMessage = e.message
        } finally {
            isLoading = false
        }
    }

    fun onGenerateProduct(product: MockupCatalogProduct) {
        if (ownerId.isBlank() || photos.isEmpty()) {
            errorMessage = t("creator.my_mockups.need_photo", "Upload a profile photo first.")
            return
        }
        isGenerating = true
        generatingProgress = t("creator.my_mockups.generating", "Generating…")
        scope.launch {
            try {
                val photoIds = photos.map { it.id }
                val resp = api.generateCustomerMockupsForProduct(ownerId, product.productKey, photoIds)
                if (!resp.optBoolean("ok", false)) {
                    errorMessage = resp.optString("error", "Generation failed")
                    return@launch
                }
                val jobId = resp.optString("job_id", "")
                val total = resp.optInt("total_products", photoIds.size).coerceAtLeast(1)
                var done = false
                while (!done) {
                    delay(3000)
                    val poll = api.pollJob(jobId)
                    val completed = poll.optInt("completed_products", 0)
                    generatingProgress = "$completed / $total"
                    done = poll.optBoolean("done", false)
                }
                CustomerMockPreviewStore.invalidate()
                reloadCatalog(api, ownerId) { p, g, a, auto, count ->
                    photos = p
                    generated = g
                    available = a
                    autoMockEnabled = auto
                    wearingMockCount = count
                }
            } catch (e: Exception) {
                errorMessage = e.message ?: "Generation failed"
            } finally {
                isGenerating = false
            }
        }
    }

    fun openLightbox(product: MockupCatalogProduct) {
        lightboxProduct = product
        lightboxVariants = product.variants
        lightboxIndex = 0
        if (product.variants.isNotEmpty()) return
        scope.launch {
            try {
                val resp = api.listCustomerMockups(ownerId, product.productKey)
                if (resp.optBoolean("ok", false)) {
                    lightboxVariants = parseVariantsForProduct(resp, product.productKey)
                }
            } catch (e: Exception) {
                DebugLog.w("AccountMockupsTab lightbox variants: ${e.message}")
            }
        }
    }

    fun onToggleAutoMock(enabled: Boolean) {
        scope.launch {
            try {
                val resp = api.toggleAutoMockDisplay(ownerId, enabled)
                if (resp.optBoolean("ok", false)) {
                    autoMockEnabled = resp.optBoolean("auto_mock_enabled", enabled)
                    wearingMockCount = resp.optInt("wearing_mock_count", wearingMockCount)
                    generated = generated.map { row ->
                        row.copy(
                            shopPreviewEnabled = autoMockEnabled && row.previewCount > 0
                        )
                    }
                    CustomerMockPreviewStore.invalidate()
                } else {
                    reload()
                }
            } catch (_: Exception) {
                reload()
            }
        }
    }

    fun onToggleMockPreview(mockupId: Long, enabling: Boolean) {
        val productKey = lightboxProduct?.productKey ?: return
        val currentCount = generated.find { it.productKey == productKey }?.previewCount ?: 0
        if (enabling && currentCount >= MockupPreviewPool.MAX_PREVIEW_MOCKS_PER_PRODUCT) {
            errorMessage = t(
                "creator.my_mockups.max_preview_mocks",
                "You can enable up to 5 mocks per product."
            )
            return
        }
        lightboxVariants = lightboxVariants.map { v ->
            if (v.id == mockupId) v.copy(useAsPreview = enabling) else v
        }
        scope.launch {
            try {
                val resp = api.toggleMockupPreview(ownerId, mockupId, enabling)
                if (resp.optBoolean("ok", false)) {
                    val count = resp.optInt("preview_count", currentCount)
                    generated = generated.map { row ->
                        if (row.productKey == productKey) {
                            row.copy(
                                previewCount = count,
                                shopPreviewEnabled = row.shopPreviewEnabled || count > 0,
                                variants = lightboxVariants
                            )
                        } else row
                    }
                    CustomerMockPreviewStore.invalidate()
                } else if (resp.optString("error") == "max_preview_mocks") {
                    errorMessage = t(
                        "creator.my_mockups.max_preview_mocks",
                        "You can enable up to 5 mocks per product."
                    )
                    reload()
                } else {
                    reload()
                }
            } catch (_: Exception) {
                reload()
            }
        }
    }

    fun onDelete(product: MockupCatalogProduct) {
        val mockupId = product.activeMockupId ?: return
        deleteConfirm = null
        lightboxProduct = null
        scope.launch {
            try {
                val resp = api.deleteCustomerMockup(ownerId, mockupId)
                if (resp.optBoolean("ok", false)) {
                    CustomerMockPreviewStore.invalidate()
                    reload()
                } else {
                    errorMessage = resp.optString("error", "Delete failed")
                }
            } catch (e: Exception) {
                errorMessage = e.message
            }
        }
    }

    Column(
        modifier = modifier
            .fillMaxWidth()
            .verticalScroll(rememberScrollState())
            .padding(8.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = t("creator.my_mockups.title", "My Mockups"),
            style = MaterialTheme.typography.titleMedium,
            color = EazColors.TextPrimary
        )
        Text(
            text = t(
                "creator.my_mockups.subtitle",
                "Upload photos, generate mocks per product, and set Wearing for shop preview."
            ),
            style = MaterialTheme.typography.bodySmall,
            color = EazColors.TextSecondary
        )

        if (ownerId.isBlank()) {
            Text(
                t("creator.my_mockups.login_required", "Please log in to use My Mockups."),
                color = EazColors.TextSecondary
            )
            return@Column
        }

        if (isGenerating) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                CircularProgressIndicator(modifier = Modifier.size(24.dp), color = EazColors.Orange)
                Spacer(Modifier.width(12.dp))
                Text(generatingProgress, style = MaterialTheme.typography.bodySmall)
            }
        }

        errorMessage?.let {
            Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
        }

        Text(t("creator.my_mockups.photos", "Profile photos"), style = MaterialTheme.typography.labelLarge)
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .horizontalScroll(rememberScrollState()),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            photos.forEach { photo ->
                Box(
                    modifier = Modifier
                        .size(72.dp)
                        .clip(RoundedCornerShape(8.dp))
                ) {
                    AsyncImage(
                        model = photo.url,
                        contentDescription = null,
                        modifier = Modifier.fillMaxSize(),
                        contentScale = ContentScale.Crop
                    )
                }
            }
            OutlinedButton(onClick = { photoPicker.launch("image/*") }) {
                Icon(Icons.Default.Add, contentDescription = null, modifier = Modifier.size(18.dp))
                Spacer(Modifier.width(4.dp))
                Text(t("creator.my_mockups.add_photo", "Add photo"))
            }
        }

        if (isLoading) {
            CircularProgressIndicator(color = EazColors.Orange, modifier = Modifier.padding(24.dp))
        } else {
            if (generated.isNotEmpty()) {
                AutoMockControlRow(
                    enabled = autoMockEnabled,
                    wearingCount = wearingMockCount,
                    t = t,
                    onToggle = { onToggleAutoMock(it) }
                )
                Text(
                    t("creator.my_mockups.generated", "My mocks"),
                    style = MaterialTheme.typography.labelLarge,
                    modifier = Modifier.padding(top = 8.dp)
                )
                MockupProductGrid(
                    products = generated,
                    onOpen = { openLightbox(it) },
                    onDelete = { deleteConfirm = it }
                )
            }
            if (available.isNotEmpty()) {
                Text(
                    t("creator.my_mockups.available", "Available products"),
                    style = MaterialTheme.typography.labelLarge,
                    modifier = Modifier.padding(top = 8.dp)
                )
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    available.forEach { product ->
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
                        ) {
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(8.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                AsyncImage(
                                    model = product.templateUrl ?: product.mockupUrl,
                                    contentDescription = null,
                                    modifier = Modifier
                                        .size(56.dp)
                                        .clip(RoundedCornerShape(8.dp)),
                                    contentScale = ContentScale.Crop
                                )
                                Column(modifier = Modifier.weight(1f).padding(horizontal = 8.dp)) {
                                    Text(
                                        product.productName,
                                        style = MaterialTheme.typography.bodySmall,
                                        maxLines = 2
                                    )
                                }
                                Button(
                                    onClick = { onGenerateProduct(product) },
                                    enabled = !isGenerating && photos.isNotEmpty()
                                ) {
                                    Text(t("creator.my_mockups.generate", "Generate"))
                                }
                            }
                        }
                    }
                }
            }
            if (generated.isEmpty() && available.isEmpty()) {
                Text(
                    t("creator.my_mockups.empty", "No products in catalog."),
                    color = EazColors.TextSecondary
                )
            }
        }
    }

    lightboxProduct?.let { product ->
        val variants = lightboxVariants.ifEmpty { product.variants }
        val idx = lightboxIndex.coerceIn(0, (variants.size - 1).coerceAtLeast(0))
        val current = variants.getOrNull(idx)
        val imageUrl = current?.mockupUrl ?: product.mockupUrl ?: product.templateUrl
        val previewCount = generated.find { it.productKey == product.productKey }?.previewCount
            ?: variants.count { it.useAsPreview }
        val wearActive = current?.useAsPreview == true
        val wearDisabled = !wearActive && previewCount >= MockupPreviewPool.MAX_PREVIEW_MOCKS_PER_PRODUCT

        AlertDialog(
            onDismissRequest = {
                lightboxProduct = null
                lightboxVariants = emptyList()
                lightboxIndex = 0
            },
            title = { Text(product.productName) },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .aspectRatio(1f)
                            .clip(RoundedCornerShape(8.dp))
                    ) {
                        if (!imageUrl.isNullOrBlank()) {
                            AsyncImage(
                                model = imageUrl,
                                contentDescription = null,
                                modifier = Modifier.fillMaxSize(),
                                contentScale = ContentScale.Crop
                            )
                        }
                        if (variants.size > 1) {
                            IconButton(
                                onClick = {
                                    lightboxIndex = (idx - 1 + variants.size) % variants.size
                                },
                                modifier = Modifier
                                    .align(Alignment.CenterStart)
                                    .padding(4.dp)
                                    .background(Color.White.copy(alpha = 0.9f), RoundedCornerShape(50))
                            ) {
                                Icon(Icons.Default.ChevronLeft, contentDescription = null)
                            }
                            IconButton(
                                onClick = {
                                    lightboxIndex = (idx + 1) % variants.size
                                },
                                modifier = Modifier
                                    .align(Alignment.CenterEnd)
                                    .padding(4.dp)
                                    .background(Color.White.copy(alpha = 0.9f), RoundedCornerShape(50))
                            ) {
                                Icon(Icons.Default.ChevronRight, contentDescription = null)
                            }
                        }
                        if (current != null) {
                            IconButton(
                                onClick = {
                                    if (!wearDisabled) {
                                        onToggleMockPreview(current.id, !wearActive)
                                    }
                                },
                                enabled = !wearDisabled,
                                modifier = Modifier
                                    .align(Alignment.BottomCenter)
                                    .padding(bottom = 8.dp)
                                    .background(
                                        if (wearActive) Color(0xFF111827) else Color.White.copy(alpha = 0.92f),
                                        RoundedCornerShape(50)
                                    )
                            ) {
                                HangerIcon(
                                    color = if (wearActive) Color.White else Color(0xFF374151),
                                    size = 22.dp
                                )
                            }
                        }
                    }
                    if (variants.size > 1) {
                        Text(
                            "${idx + 1} / ${variants.size}",
                            style = MaterialTheme.typography.labelSmall,
                            color = EazColors.TextSecondary,
                            modifier = Modifier.align(Alignment.CenterHorizontally)
                        )
                    }
                }
            },
            confirmButton = {
                TextButton(onClick = {
                    lightboxProduct = null
                    lightboxVariants = emptyList()
                    lightboxIndex = 0
                }) {
                    Text(t("creator.common.close", "Close"))
                }
            }
        )
    }

    deleteConfirm?.let { product ->
        AlertDialog(
            onDismissRequest = { deleteConfirm = null },
            title = { Text(t("creator.my_mockups.delete_title", "Delete mockup?")) },
            text = { Text(t("creator.my_mockups.delete_body", "This mockup will be permanently deleted.")) },
            confirmButton = {
                TextButton(onClick = { onDelete(product) }) {
                    Text(t("creator.common.delete", "Delete"), color = MaterialTheme.colorScheme.error)
                }
            },
            dismissButton = {
                TextButton(onClick = { deleteConfirm = null }) {
                    Text(t("creator.common.cancel", "Cancel"))
                }
            }
        )
    }
}

@Composable
private fun AutoMockControlRow(
    enabled: Boolean,
    wearingCount: Int,
    t: (String, String) -> String,
    onToggle: (Boolean) -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(top = 8.dp),
        colors = CardDefaults.cardColors(containerColor = Color(0xFFF9FAFB))
    ) {
        Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                HangerIcon(color = Color(0xFF111827), size = 22.dp)
                Text(
                    t("creator.my_mockups.auto_mock_label", "Auto mock"),
                    style = MaterialTheme.typography.titleSmall,
                    color = Color(0xFF111827)
                )
            }
            Row(
                modifier = Modifier.fillMaxWidth().padding(start = 32.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = wearingCount.toString(),
                    style = MaterialTheme.typography.headlineSmall,
                    color = Color(0xFF111827)
                )
                Switch(
                    checked = enabled,
                    onCheckedChange = onToggle,
                    enabled = wearingCount > 0
                )
            }
        }
    }
}

@Composable
private fun MockupProductGrid(
    products: List<MockupCatalogProduct>,
    onOpen: (MockupCatalogProduct) -> Unit,
    onDelete: (MockupCatalogProduct) -> Unit
) {
    products.chunked(2).forEach { row ->
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            row.forEach { product ->
                Card(
                    modifier = Modifier
                        .weight(1f)
                        .aspectRatio(0.85f)
                        .clickable { onOpen(product) },
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column {
                        Box(modifier = Modifier.weight(1f).fillMaxWidth()) {
                            val url = product.mockupUrl ?: product.templateUrl
                            if (!url.isNullOrBlank()) {
                                AsyncImage(
                                    model = url,
                                    contentDescription = null,
                                    modifier = Modifier.fillMaxSize(),
                                    contentScale = ContentScale.Crop
                                )
                            } else {
                                Box(
                                    Modifier
                                        .fillMaxSize()
                                        .background(EazColors.TopbarBorder.copy(alpha = 0.3f)),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Icon(Icons.Default.Image, null, tint = EazColors.TextSecondary)
                                }
                            }
                        }
                        Row(
                            modifier = Modifier.fillMaxWidth().padding(6.dp),
                            horizontalArrangement = Arrangement.End,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            IconButton(onClick = { onDelete(product) }, modifier = Modifier.size(32.dp)) {
                                Icon(Icons.Default.Delete, null, modifier = Modifier.size(16.dp))
                            }
                        }
                    }
                }
            }
            if (row.size == 1) Spacer(Modifier.weight(1f))
        }
    }
}

private suspend fun reloadCatalog(
    api: com.eazpire.creator.api.CreatorApi,
    ownerId: String,
    onResult: (
        List<MockupProfilePhoto>,
        List<MockupCatalogProduct>,
        List<MockupCatalogProduct>,
        Boolean,
        Int
    ) -> Unit
) {
    val photosResp = api.listMockupPhotos(ownerId)
    val photos = if (photosResp.optBoolean("ok", false)) {
        parsePhotos(photosResp.optJSONArray("photos"))
    } else emptyList()

    val variantsByProduct = mutableMapOf<String, List<MockupVariant>>()
    runCatching {
        val mockupsResp = api.listCustomerMockups(ownerId)
        if (mockupsResp.optBoolean("ok", false)) {
            val products = mockupsResp.optJSONArray("products")
            if (products != null) {
                for (i in 0 until products.length()) {
                    val p = products.optJSONObject(i) ?: continue
                    val pk = p.optString("product_key", "")
                    if (pk.isBlank()) continue
                    variantsByProduct[pk] = parseVariantsArray(p.optJSONArray("variants"))
                }
            }
        }
    }

    val prodResp = api.listMockupProducts(ownerId)
    val generated = mutableListOf<MockupCatalogProduct>()
    val available = mutableListOf<MockupCatalogProduct>()
    var autoMock = true
    var wearingCount = 0
    if (prodResp.optBoolean("ok", false)) {
        autoMock = prodResp.optBoolean("auto_mock_enabled", true)
        wearingCount = prodResp.optInt("wearing_mock_count", 0)
        parseCatalogProducts(prodResp.optJSONArray("generated"), true, generated, variantsByProduct)
        parseCatalogProducts(prodResp.optJSONArray("available"), false, available, variantsByProduct)
    }
    onResult(photos, generated, available, autoMock, wearingCount)
}

private fun parsePhotos(arr: JSONArray?): List<MockupProfilePhoto> {
    if (arr == null) return emptyList()
    return (0 until arr.length()).mapNotNull { i ->
        val o = arr.optJSONObject(i) ?: return@mapNotNull null
        val id = o.optLong("id", -1L)
        if (id < 0) return@mapNotNull null
        MockupProfilePhoto(
            id = id,
            url = o.optString("url", ""),
            personType = o.optString("person_type").takeIf { it.isNotBlank() }
        )
    }
}

private fun parseVariantsArray(arr: JSONArray?): List<MockupVariant> {
    if (arr == null) return emptyList()
    return (0 until arr.length()).mapNotNull { i ->
        val o = arr.optJSONObject(i) ?: return@mapNotNull null
        val id = o.optLong("id", -1L)
        if (id < 0) return@mapNotNull null
        MockupVariant(
            id = id,
            mockupUrl = o.optString("mockup_url").takeIf { it.isNotBlank() },
            useAsPreview = o.optBoolean("use_as_preview", false)
        )
    }
}

private fun parseVariantsForProduct(resp: org.json.JSONObject, productKey: String): List<MockupVariant> {
    val products = resp.optJSONArray("products") ?: return emptyList()
    for (i in 0 until products.length()) {
        val p = products.optJSONObject(i) ?: continue
        if (p.optString("product_key") == productKey) {
            return parseVariantsArray(p.optJSONArray("variants"))
        }
    }
    return emptyList()
}

private fun parseCatalogProducts(
    arr: JSONArray?,
    isGenerated: Boolean,
    out: MutableList<MockupCatalogProduct>,
    variantsByProduct: Map<String, List<MockupVariant>>
) {
    if (arr == null) return
    for (i in 0 until arr.length()) {
        val o = arr.optJSONObject(i) ?: continue
        val pk = o.optString("product_key", "")
        if (pk.isBlank()) continue
        val variants = variantsByProduct[pk].orEmpty()
        val previewCount = if (o.has("preview_count")) {
            o.optInt("preview_count", 0)
        } else {
            variants.count { it.useAsPreview }
        }
        out.add(
            MockupCatalogProduct(
                productKey = pk,
                productName = o.optString("product_name", pk),
                mockupUrl = o.optString("mockup_url").takeIf { it.isNotBlank() },
                templateUrl = o.optString("template_url").takeIf { it.isNotBlank() },
                activeMockupId = o.optLong("active_mockup_id", -1L).takeIf { it > 0 },
                previewCount = previewCount,
                shopPreviewEnabled = o.optBoolean("shop_preview_enabled", previewCount > 0),
                isGenerated = isGenerated,
                status = o.optString("status").takeIf { it.isNotBlank() },
                variants = variants
            )
        )
    }
}
