package com.eazpire.creator.ui.account

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.ChevronLeft
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Image
import com.eazpire.creator.ui.modal.EazInsetDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Tab
import androidx.compose.material3.TabRow
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage
import com.eazpire.creator.EazColors
import com.eazpire.creator.auth.SecureTokenStore
import com.eazpire.creator.i18n.LocalTranslationStore
import com.eazpire.creator.mockup.CustomerMockPreviewStore
import com.eazpire.creator.mockup.MockupPreviewPool
import com.eazpire.creator.ui.components.HangerIcon
import com.eazpire.creator.util.DebugLog
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import org.json.JSONArray

/**
 * My Mockups — aligned with web [my-mockups.js]:
 * photo library, per-product generate, Wearing toggle, shared backend ops.
 */
data class MockupProfilePhoto(
    val id: Long,
    val url: String,
    val personType: String?
)

data class MockupVariant(
    val id: Long,
    val mockupUrl: String?,
    val useAsPreview: Boolean
)

data class MockupCatalogProduct(
    val productKey: String,
    val productName: String,
    val mockupUrl: String?,
    val templateUrl: String?,
    val activeMockupId: Long?,
    val previewCount: Int,
    val shopPreviewEnabled: Boolean,
    val isGenerated: Boolean,
    val status: String?,
    val variants: List<MockupVariant> = emptyList()
) {
    val shopPreviewActive: Boolean get() = shopPreviewEnabled
}

@Composable
fun AccountMockupsTab(
    tokenStore: SecureTokenStore,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val store = LocalTranslationStore.current
    val t = store?.let { { k: String, d: String -> it.t(k, d) } } ?: { _: String, d: String -> d }
    val jwt = remember { runCatching { tokenStore.getJwt() }.getOrNull() }
    val ownerId = remember { runCatching { tokenStore.getOwnerId() }.getOrNull() ?: "" }

    var photos by remember { mutableStateOf<List<MockupProfilePhoto>>(emptyList()) }
    var generated by remember { mutableStateOf<List<MockupCatalogProduct>>(emptyList()) }
    var available by remember { mutableStateOf<List<MockupCatalogProduct>>(emptyList()) }
    var isLoading by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf<String?>(null) }
    var uploadPersonType by remember { mutableStateOf("woman") }
    var isGenerating by remember { mutableStateOf(false) }
    var generatingProgress by remember { mutableStateOf("") }
    var lightboxProduct by remember { mutableStateOf<MockupCatalogProduct?>(null) }
    var lightboxVariants by remember { mutableStateOf<List<MockupVariant>>(emptyList()) }
    var lightboxIndex by remember { mutableStateOf(0) }
    var lightboxLoading by remember { mutableStateOf(false) }
    var deleteConfirm by remember { mutableStateOf<MockupCatalogProduct?>(null) }
    var showShopPreviewComingSoon by remember { mutableStateOf(false) }
    var selectedTab by remember { mutableIntStateOf(0) }

    val api = remember(jwt) { com.eazpire.creator.api.CreatorApi(jwt = jwt) }
    val scope = rememberCoroutineScope()

    val photoPicker = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        if (uri == null || ownerId.isBlank()) return@rememberLauncherForActivityResult
        scope.launch {
            isGenerating = true
            generatingProgress = t("creator.my_mockups.uploading", "Uploading photo…")
            errorMessage = null
            try {
                val bytes = context.contentResolver.openInputStream(uri)?.use { it.readBytes() }
                    ?: throw IllegalArgumentException("Could not read photo")
                val contentType = context.contentResolver.getType(uri) ?: "image/jpeg"
                val resp = api.uploadMockupPhoto(ownerId, bytes, contentType, uploadPersonType)
                if (!resp.optBoolean("ok", false)) {
                    errorMessage = resp.optString("error", "Upload failed")
                } else {
                    reloadCatalog(api, ownerId) { p, g, a ->
                        photos = p
                        generated = g
                        available = a
                    }
                }
            } catch (e: Exception) {
                DebugLog.click("Mockup upload error: ${e.message}")
                errorMessage = e.message ?: "Upload failed"
            } finally {
                isGenerating = false
            }
        }
    }

    fun reload() {
        scope.launch {
            if (ownerId.isBlank()) return@launch
            isLoading = true
            errorMessage = null
            try {
                reloadCatalog(api, ownerId) { p, g, a ->
                    photos = p
                    generated = g
                    available = a
                }
            } catch (e: Exception) {
                errorMessage = e.message ?: "Failed to load"
            } finally {
                isLoading = false
            }
        }
    }

    LaunchedEffect(ownerId) {
        if (ownerId.isBlank()) return@LaunchedEffect
        isLoading = true
        try {
            reloadCatalog(api, ownerId) { p, g, a ->
                photos = p
                generated = g
                available = a
            }
        } catch (e: Exception) {
            errorMessage = e.message
        } finally {
            isLoading = false
        }
    }

    fun onGenerateProduct(product: MockupCatalogProduct) {
        if (ownerId.isBlank() || photos.isEmpty()) {
            errorMessage = t("creator.my_mockups.need_photo", "Upload a profile photo first.")
            return
        }
        isGenerating = true
        generatingProgress = t("creator.my_mockups.generating", "Generating…")
        scope.launch {
            try {
                val photoIds = photos.map { it.id }
                val resp = api.generateCustomerMockupsForProduct(ownerId, product.productKey, photoIds)
                if (!resp.optBoolean("ok", false)) {
                    errorMessage = resp.optString("error", "Generation failed")
                    return@launch
                }
                val jobId = resp.optString("job_id", "")
                val total = resp.optInt("total_products", photoIds.size).coerceAtLeast(1)
                var done = false
                while (!done) {
                    delay(3000)
                    val poll = api.pollJob(jobId)
                    val completed = poll.optInt("completed_products", 0)
                    generatingProgress = "$completed / $total"
                    done = poll.optBoolean("done", false)
                }
                CustomerMockPreviewStore.invalidate()
                reloadCatalog(api, ownerId) { p, g, a ->
                    photos = p
                    generated = g
                    available = a
                }
            } catch (e: Exception) {
                errorMessage = e.message ?: "Generation failed"
            } finally {
                isGenerating = false
            }
        }
    }

    fun openLightbox(product: MockupCatalogProduct) {
        lightboxProduct = product
        lightboxVariants = product.variants.filter { !it.mockupUrl.isNullOrBlank() }
        lightboxIndex = 0
        lightboxLoading = true
        scope.launch {
            try {
                val resp = api.listCustomerMockups(ownerId, product.productKey)
                if (resp.optBoolean("ok", false)) {
                    val loaded = parseVariantsForProduct(resp, product.productKey)
                        .filter { !it.mockupUrl.isNullOrBlank() }
                    if (loaded.isNotEmpty()) {
                        lightboxVariants = loaded
                        val activeId = product.activeMockupId
                        if (activeId != null) {
                            val idx = loaded.indexOfFirst { it.id == activeId }
                            if (idx >= 0) lightboxIndex = idx
                        }
                    }
                }
            } catch (e: Exception) {
                DebugLog.w("AccountMockupsTab lightbox variants: ${e.message}")
            } finally {
                lightboxLoading = false
            }
        }
    }

    fun onToggleProductShopPreview(productKey: String, enabled: Boolean) {
        if (enabled) {
            showShopPreviewComingSoon = true
            return
        }
        scope.launch {
            try {
                val resp = api.toggleProductShopPreview(ownerId, productKey, enabled)
                if (resp.optBoolean("ok", false)) {
                    val shopEnabled = resp.optBoolean("shop_preview_enabled", enabled)
                    val count = resp.optInt("preview_count", 0)
                    generated = generated.map { row ->
                        if (row.productKey == productKey) {
                            row.copy(
                                previewCount = count,
                                shopPreviewEnabled = shopEnabled && count > 0
                            )
                        } else row
                    }
                    CustomerMockPreviewStore.invalidate()
                } else {
                    reload()
                }
            } catch (_: Exception) {
                reload()
            }
        }
    }

    fun onToggleMockPreview(mockupId: Long, enabling: Boolean) {
        val productKey = lightboxProduct?.productKey ?: return
        val currentCount = generated.find { it.productKey == productKey }?.previewCount ?: 0
        if (enabling && currentCount >= MockupPreviewPool.MAX_PREVIEW_MOCKS_PER_PRODUCT) {
            errorMessage = t(
                "creator.my_mockups.max_preview_mocks",
                "You can enable up to 5 mocks per product."
            )
            return
        }
        lightboxVariants = lightboxVariants.map { v ->
            if (v.id == mockupId) v.copy(useAsPreview = enabling) else v
        }
        scope.launch {
            try {
                val resp = api.toggleMockupPreview(ownerId, mockupId, enabling)
                if (resp.optBoolean("ok", false)) {
                    val count = resp.optInt("preview_count", currentCount)
                    generated = generated.map { row ->
                        if (row.productKey == productKey) {
                            row.copy(
                                previewCount = count,
                                shopPreviewEnabled = row.shopPreviewEnabled || count > 0,
                                variants = lightboxVariants
                            )
                        } else row
                    }
                    CustomerMockPreviewStore.invalidate()
                } else if (resp.optString("error") == "max_preview_mocks") {
                    errorMessage = t(
                        "creator.my_mockups.max_preview_mocks",
                        "You can enable up to 5 mocks per product."
                    )
                    reload()
                } else {
                    reload()
                }
            } catch (_: Exception) {
                reload()
            }
        }
    }

    fun onDelete(product: MockupCatalogProduct) {
        val mockupId = product.activeMockupId ?: return
        deleteConfirm = null
        lightboxProduct = null
        scope.launch {
            try {
                val resp = api.deleteCustomerMockup(ownerId, mockupId)
                if (resp.optBoolean("ok", false)) {
                    CustomerMockPreviewStore.invalidate()
                    reload()
                } else {
                    errorMessage = resp.optString("error", "Delete failed")
                }
            } catch (e: Exception) {
                errorMessage = e.message
            }
        }
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(8.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = t("creator.my_mockups.title", "My Mockups"),
            style = MaterialTheme.typography.titleMedium,
            color = EazColors.TextPrimary
        )
        Text(
            text = t(
                "creator.my_mockups.subtitle",
                "Upload photos, generate mocks per product, and set Wearing for shop preview."
            ),
            style = MaterialTheme.typography.bodySmall,
            color = EazColors.TextSecondary
        )

        if (ownerId.isBlank()) {
            Text(
                t("creator.my_mockups.login_required", "Please log in to use My Mockups."),
                color = EazColors.TextSecondary
            )
            return@Column
        }

        if (isGenerating) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                CircularProgressIndicator(modifier = Modifier.size(24.dp), color = EazColors.Orange)
                Spacer(Modifier.width(12.dp))
                Text(generatingProgress, style = MaterialTheme.typography.bodySmall)
            }
        }

        errorMessage?.let {
            Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
        }

        val tabLabels = listOf(
            t("size_ai.tab_reference_images", "Reference Images"),
            t("size_ai.tab_generated_mockups", "Generated Mockups"),
            t("size_ai.tab_available_products", "Available Products")
        )
        TabRow(selectedTabIndex = selectedTab) {
            tabLabels.forEachIndexed { index, label ->
                Tab(
                    selected = selectedTab == index,
                    onClick = { selectedTab = index },
                    text = { Text(label, maxLines = 1, style = MaterialTheme.typography.labelSmall) }
                )
            }
        }

        when (selectedTab) {
            0 -> {
                Text(t("creator.my_mockups.photos", "Profile photos"), style = MaterialTheme.typography.labelLarge)
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    photos.forEach { photo ->
                        Box(
                            modifier = Modifier
                                .size(72.dp)
                                .clip(RoundedCornerShape(8.dp))
                        ) {
                            AsyncImage(
                                model = photo.url,
                                contentDescription = null,
                                modifier = Modifier.fillMaxSize(),
                                contentScale = ContentScale.Crop
                            )
                        }
                    }
                    OutlinedButton(onClick = { photoPicker.launch("image/*") }) {
                        Icon(Icons.Default.Add, contentDescription = null, modifier = Modifier.size(18.dp))
                        Spacer(Modifier.width(4.dp))
                        Text(t("creator.my_mockups.add_photo", "Add photo"))
                    }
                }
            }
            1 -> {
                if (isLoading) {
                    CircularProgressIndicator(color = EazColors.Orange, modifier = Modifier.padding(24.dp))
                } else if (generated.isEmpty()) {
                    Text(
                        t("size_ai.no_mockups_yet", "No mockups yet"),
                        color = EazColors.TextSecondary
                    )
                } else {
                    MockupProductGrid(
                        products = generated,
                        showAutoMock = true,
                        canGenerate = !isGenerating && photos.isNotEmpty(),
                        t = t,
                        onOpen = { openLightbox(it) },
                        onGenerate = { onGenerateProduct(it) },
                        onToggleAutoMock = { product, enabled ->
                            onToggleProductShopPreview(product.productKey, enabled)
                        }
                    )
                }
            }
            else -> {
                if (isLoading) {
                    CircularProgressIndicator(color = EazColors.Orange, modifier = Modifier.padding(24.dp))
                } else if (available.isEmpty()) {
                    Text(
                        t("size_ai.no_available_products", "No products available for mockup generation"),
                        color = EazColors.TextSecondary
                    )
                } else {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        available.forEach { product ->
                            Card(
                                modifier = Modifier.fillMaxWidth(),
                                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
                            ) {
                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .padding(8.dp),
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    AsyncImage(
                                        model = product.templateUrl ?: product.mockupUrl,
                                        contentDescription = null,
                                        modifier = Modifier
                                            .size(56.dp)
                                            .clip(RoundedCornerShape(8.dp)),
                                        contentScale = ContentScale.Crop
                                    )
                                    Column(modifier = Modifier.weight(1f).padding(horizontal = 8.dp)) {
                                        Text(
                                            product.productName,
                                            style = MaterialTheme.typography.bodySmall,
                                            maxLines = 2
                                        )
                                    }
                                    Button(
                                        onClick = { onGenerateProduct(product) },
                                        enabled = !isGenerating && photos.isNotEmpty()
                                    ) {
                                        Text(t("creator.my_mockups.generate", "Generate"))
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    lightboxProduct?.let { product ->
        val variants = lightboxVariants.filter { !it.mockupUrl.isNullOrBlank() }
        val idx = if (variants.isEmpty()) 0 else lightboxIndex.coerceIn(0, variants.size - 1)
        val current = variants.getOrNull(idx)
        val imageUrl = current?.mockupUrl ?: product.mockupUrl ?: product.templateUrl
        val previewCount = generated.find { it.productKey == product.productKey }?.previewCount
            ?: variants.count { it.useAsPreview }
        val wearActive = current?.useAsPreview == true
        val wearDisabled = !wearActive && previewCount >= MockupPreviewPool.MAX_PREVIEW_MOCKS_PER_PRODUCT

        EazInsetDialog(
            onDismissRequest = {
                lightboxProduct = null
                lightboxVariants = emptyList()
                lightboxIndex = 0
                lightboxLoading = false
            },
        ) {
            Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Column(
                modifier = Modifier
                    .fillMaxWidth(0.94f)
                    .clip(RoundedCornerShape(16.dp))
                    .background(Color.White)
                    .padding(12.dp)
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        product.productName,
                        style = MaterialTheme.typography.titleMedium,
                        modifier = Modifier.weight(1f),
                        maxLines = 2
                    )
                    IconButton(onClick = {
                        lightboxProduct = null
                        lightboxVariants = emptyList()
                        lightboxIndex = 0
                        lightboxLoading = false
                    }) {
                        Icon(Icons.Default.Close, contentDescription = t("creator.common.close", "Close"))
                    }
                }
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .aspectRatio(1f)
                        .clip(RoundedCornerShape(8.dp))
                        .background(Color(0xFFF3F4F6))
                ) {
                    when {
                        lightboxLoading -> {
                            CircularProgressIndicator(
                                modifier = Modifier.align(Alignment.Center),
                                color = EazColors.Orange
                            )
                        }
                        !imageUrl.isNullOrBlank() -> {
                            AsyncImage(
                                model = imageUrl,
                                contentDescription = null,
                                modifier = Modifier.fillMaxSize(),
                                contentScale = ContentScale.Crop
                            )
                        }
                        else -> {
                            Icon(
                                Icons.Default.Image,
                                contentDescription = null,
                                modifier = Modifier.align(Alignment.Center),
                                tint = EazColors.TextSecondary
                            )
                        }
                    }
                    if (!lightboxLoading && variants.size > 1) {
                        IconButton(
                            onClick = {
                                lightboxIndex = (idx - 1 + variants.size) % variants.size
                            },
                            modifier = Modifier
                                .align(Alignment.CenterStart)
                                .padding(4.dp)
                                .background(Color.White.copy(alpha = 0.92f), RoundedCornerShape(50))
                        ) {
                            Icon(Icons.Default.ChevronLeft, contentDescription = null)
                        }
                        IconButton(
                            onClick = {
                                lightboxIndex = (idx + 1) % variants.size
                            },
                            modifier = Modifier
                                .align(Alignment.CenterEnd)
                                .padding(4.dp)
                                .background(Color.White.copy(alpha = 0.92f), RoundedCornerShape(50))
                        ) {
                            Icon(Icons.Default.ChevronRight, contentDescription = null)
                        }
                    }
                    if (current != null && !lightboxLoading) {
                        IconButton(
                            onClick = {
                                if (!wearDisabled) {
                                    onToggleMockPreview(current.id, !wearActive)
                                }
                            },
                            enabled = !wearDisabled,
                            modifier = Modifier
                                .align(Alignment.BottomCenter)
                                .padding(bottom = 8.dp)
                                .background(
                                    if (wearActive) Color(0xFF111827) else Color.White.copy(alpha = 0.92f),
                                    RoundedCornerShape(50)
                                )
                        ) {
                            HangerIcon(
                                color = if (wearActive) Color.White else Color(0xFF374151),
                                size = 22.dp
                            )
                        }
                    }
                }
                if (!lightboxLoading && variants.size > 1) {
                    Text(
                        "${idx + 1} / ${variants.size}",
                        style = MaterialTheme.typography.labelSmall,
                        color = EazColors.TextSecondary,
                        modifier = Modifier
                            .align(Alignment.CenterHorizontally)
                            .padding(top = 8.dp)
                    )
                }
            }
            }
        }
    }

    deleteConfirm?.let { product ->
        androidx.compose.material3.AlertDialog(
            onDismissRequest = { deleteConfirm = null },
            title = { Text(t("creator.my_mockups.delete_title", "Delete mockup?")) },
            text = { Text(t("creator.my_mockups.delete_body", "This mockup will be permanently deleted.")) },
            confirmButton = {
                TextButton(onClick = { onDelete(product) }) {
                    Text(t("creator.common.delete", "Delete"), color = MaterialTheme.colorScheme.error)
                }
            },
            dismissButton = {
                TextButton(onClick = { deleteConfirm = null }) {
                    Text(t("creator.common.cancel", "Cancel"))
                }
            }
        )
    }

    if (showShopPreviewComingSoon) {
        androidx.compose.material3.AlertDialog(
            onDismissRequest = { showShopPreviewComingSoon = false },
            title = { Text(t("size_ai.shop_preview_coming_soon_title", "Coming soon")) },
            text = {
                Text(
                    t(
                        "size_ai.shop_preview_coming_soon_body",
                        "Shop preview automatically shows your personalized wearing mocks on product cards across the shop. This is not available yet — use Try on on each product for now."
                    )
                )
            },
            confirmButton = {
                TextButton(onClick = { showShopPreviewComingSoon = false }) {
                    Text(t("size_ai.close", "Close"))
                }
            }
        )
    }
}

@Composable
private fun MockupProductGrid(
    products: List<MockupCatalogProduct>,
    showAutoMock: Boolean,
    canGenerate: Boolean,
    t: (String, String) -> String,
    onOpen: (MockupCatalogProduct) -> Unit,
    onGenerate: (MockupCatalogProduct) -> Unit,
    onToggleAutoMock: (MockupCatalogProduct, Boolean) -> Unit
) {
    products.chunked(2).forEach { row ->
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            row.forEach { product ->
                Card(
                    modifier = Modifier
                        .weight(1f)
                        .aspectRatio(0.85f),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column(modifier = Modifier.fillMaxSize()) {
                        Box(
                            modifier = Modifier
                                .weight(1f)
                                .fillMaxWidth()
                                .clickable { onOpen(product) }
                        ) {
                            val url = product.mockupUrl ?: product.templateUrl
                            if (!url.isNullOrBlank()) {
                                AsyncImage(
                                    model = url,
                                    contentDescription = null,
                                    modifier = Modifier.fillMaxSize(),
                                    contentScale = ContentScale.Crop
                                )
                            } else {
                                Box(
                                    Modifier
                                        .fillMaxSize()
                                        .background(EazColors.TopbarBorder.copy(alpha = 0.3f)),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Icon(Icons.Default.Image, null, tint = EazColors.TextSecondary)
                                }
                            }
                        }
                        Text(
                            product.productName,
                            style = MaterialTheme.typography.labelSmall,
                            maxLines = 2,
                            modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp)
                        )
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(horizontal = 8.dp, vertical = 6.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Button(
                                onClick = { onGenerate(product) },
                                enabled = canGenerate,
                                modifier = Modifier.height(36.dp),
                                contentPadding = androidx.compose.foundation.layout.PaddingValues(horizontal = 10.dp)
                            ) {
                                Text(t("creator.my_mockups.generate", "Generate"), style = MaterialTheme.typography.labelSmall)
                            }
                            if (showAutoMock) {
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    Text(
                                        product.previewCount.toString(),
                                        style = MaterialTheme.typography.labelLarge,
                                        color = Color(0xFF111827)
                                    )
                                    Switch(
                                        checked = product.shopPreviewEnabled,
                                        onCheckedChange = { onToggleAutoMock(product, it) },
                                        enabled = product.previewCount > 0
                                    )
                                }
                            }
                        }
                    }
                }
            }
            if (row.size == 1) Spacer(Modifier.weight(1f))
        }
    }
}

private suspend fun reloadCatalog(
    api: com.eazpire.creator.api.CreatorApi,
    ownerId: String,
    onResult: (
        List<MockupProfilePhoto>,
        List<MockupCatalogProduct>,
        List<MockupCatalogProduct>
    ) -> Unit
) {
    val photosResp = api.listMockupPhotos(ownerId)
    val photos = if (photosResp.optBoolean("ok", false)) {
        parsePhotos(photosResp.optJSONArray("photos"))
    } else emptyList()

    val variantsByProduct = mutableMapOf<String, List<MockupVariant>>()
    runCatching {
        val mockupsResp = api.listCustomerMockups(ownerId)
        if (mockupsResp.optBoolean("ok", false)) {
            val products = mockupsResp.optJSONArray("products")
            if (products != null) {
                for (i in 0 until products.length()) {
                    val p = products.optJSONObject(i) ?: continue
                    val pk = p.optString("product_key", "")
                    if (pk.isBlank()) continue
                    variantsByProduct[pk] = parseVariantsArray(p.optJSONArray("variants"))
                }
            }
        }
    }

    val prodResp = api.listMockupProducts(ownerId)
    val generated = mutableListOf<MockupCatalogProduct>()
    val available = mutableListOf<MockupCatalogProduct>()
    if (prodResp.optBoolean("ok", false)) {
        parseCatalogProducts(prodResp.optJSONArray("generated"), true, generated, variantsByProduct)
        parseCatalogProducts(prodResp.optJSONArray("available"), false, available, variantsByProduct)
    }
    onResult(photos, generated, available)
}

private fun parsePhotos(arr: JSONArray?): List<MockupProfilePhoto> {
    if (arr == null) return emptyList()
    return (0 until arr.length()).mapNotNull { i ->
        val o = arr.optJSONObject(i) ?: return@mapNotNull null
        val id = o.optLong("id", -1L)
        if (id < 0) return@mapNotNull null
        MockupProfilePhoto(
            id = id,
            url = o.optString("url", ""),
            personType = o.optString("person_type").takeIf { it.isNotBlank() }
        )
    }
}

private fun parseVariantsArray(arr: JSONArray?): List<MockupVariant> {
    if (arr == null) return emptyList()
    return (0 until arr.length()).mapNotNull { i ->
        val o = arr.optJSONObject(i) ?: return@mapNotNull null
        val id = o.optLong("id", -1L)
        if (id < 0) return@mapNotNull null
        MockupVariant(
            id = id,
            mockupUrl = o.optString("mockup_url").takeIf { it.isNotBlank() },
            useAsPreview = o.optBoolean("use_as_preview", false)
        )
    }
}

private fun parseVariantsForProduct(resp: org.json.JSONObject, productKey: String): List<MockupVariant> {
    val products = resp.optJSONArray("products") ?: return emptyList()
    for (i in 0 until products.length()) {
        val p = products.optJSONObject(i) ?: continue
        if (p.optString("product_key") == productKey) {
            return parseVariantsArray(p.optJSONArray("variants"))
        }
    }
    return emptyList()
}

private fun parseCatalogProducts(
    arr: JSONArray?,
    isGenerated: Boolean,
    out: MutableList<MockupCatalogProduct>,
    variantsByProduct: Map<String, List<MockupVariant>>
) {
    if (arr == null) return
    for (i in 0 until arr.length()) {
        val o = arr.optJSONObject(i) ?: continue
        val pk = o.optString("product_key", "")
        if (pk.isBlank()) continue
        val variants = variantsByProduct[pk].orEmpty()
        val previewCount = if (o.has("preview_count")) {
            o.optInt("preview_count", 0)
        } else {
            variants.count { it.useAsPreview }
        }
        out.add(
            MockupCatalogProduct(
                productKey = pk,
                productName = o.optString("product_name", pk),
                mockupUrl = o.optString("mockup_url").takeIf { it.isNotBlank() },
                templateUrl = o.optString("template_url").takeIf { it.isNotBlank() },
                activeMockupId = o.optLong("active_mockup_id", -1L).takeIf { it > 0 },
                previewCount = previewCount,
                shopPreviewEnabled = o.optBoolean("shop_preview_enabled", previewCount > 0),
                isGenerated = isGenerated,
                status = o.optString("status").takeIf { it.isNotBlank() },
                variants = variants
            )
        )
    }
}
