package com.eazpire.creator.ui.creator

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.eazpire.creator.EazColors
import com.eazpire.creator.api.CreatorApi
import com.eazpire.creator.i18n.TranslationStore
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

@Composable
fun CreatorStatsSection(
    translationStore: TranslationStore,
    ownerId: String?,
    isLoggedIn: Boolean,
    onOpenSalesModal: () -> Unit,
    modifier: Modifier = Modifier
) {
    var salesEazpire by remember { mutableStateOf("–") }
    var salesAmazon by remember { mutableStateOf("–") }
    var designsGenerated by remember { mutableStateOf("–") }
    var designsUploaded by remember { mutableStateOf("–") }
    var productsOnline by remember { mutableStateOf("–") }
    var productsOffline by remember { mutableStateOf("–") }
    var heroesGenerated by remember { mutableStateOf("–") }
    var heroesOnline by remember { mutableStateOf("–") }

    if (isLoggedIn && !ownerId.isNullOrBlank()) {
        val api = remember { CreatorApi() }
        LaunchedEffect(ownerId) {
            try {
                val srcData = withContext(Dispatchers.IO) { api.getDesignSourceCounts(ownerId!!) }
                val pubData = withContext(Dispatchers.IO) { api.getPublishStats(ownerId) }
                val salesData = withContext(Dispatchers.IO) { api.getCreatorSales(ownerId) }
                val heroData = withContext(Dispatchers.IO) { api.getHeroAnalyticsSummary(ownerId, 90) }

                if (salesData.optBoolean("ok", false)) {
                    salesEazpire = (salesData.optInt("totalOrders", 0)).toString()
                    salesAmazon = "–"
                }
                if (srcData.optBoolean("ok", false)) {
                    designsGenerated = (srcData.optInt("generated", 0)).toString()
                    designsUploaded = (srcData.optInt("uploaded", 0)).toString()
                }
                if (pubData.optBoolean("ok", false)) {
                    val prods = pubData.optJSONObject("products")
                    if (prods != null) {
                        productsOnline = (prods.optInt("online", 0)).toString()
                        productsOffline = (prods.optInt("offline", 0)).toString()
                    }
                }
                if (heroData.optBoolean("ok", false)) {
                    val hc = heroData.optJSONObject("hero_count")
                    if (hc != null) {
                        heroesGenerated = (hc.optInt("total", 0)).toString()
                        heroesOnline = (hc.optInt("published", 0)).toString()
                    }
                }
            } catch (_: Exception) {}
        }
    }

    Text(
        text = translationStore.t("creator.mobile.overview", "Overview"),
        style = MaterialTheme.typography.titleSmall,
        color = Color.White,
        modifier = Modifier.padding(top = 16.dp, bottom = 8.dp)
    )

    Row(
        modifier = modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        CreatorStatCard(
            icon = "💰",
            label = translationStore.t("creator.overview.sales_label", "Sales"),
            primaryLabel = translationStore.t("creator.overview.sales_eazpire", "Eazpire"),
            primaryValue = salesEazpire,
            secondaryLabel = translationStore.t("creator.overview.sales_amazon", "Amazon"),
            secondaryValue = salesAmazon,
            onClick = if (isLoggedIn) onOpenSalesModal else null,
            modifier = Modifier.weight(1f)
        )
        CreatorStatCard(
            icon = "🎨",
            label = translationStore.t("creator.overview.designs_label", "Designs"),
            primaryLabel = translationStore.t("creator.overview.designs_generated", "Generated"),
            primaryValue = designsGenerated,
            secondaryLabel = translationStore.t("creator.overview.designs_uploaded", "Uploaded"),
            secondaryValue = designsUploaded,
            onClick = null,
            modifier = Modifier.weight(1f)
        )
    }

    Row(
        modifier = Modifier.fillMaxWidth().padding(top = 8.dp),
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        CreatorStatCard(
            icon = "📦",
            label = translationStore.t("creator.overview.products_label", "Products"),
            primaryLabel = translationStore.t("creator.overview.products_online", "Online"),
            primaryValue = productsOnline,
            secondaryLabel = translationStore.t("creator.overview.products_offline", "Offline"),
            secondaryValue = productsOffline,
            onClick = null,
            modifier = Modifier.weight(1f)
        )
        CreatorStatCard(
            icon = "🖼️",
            label = translationStore.t("creator.overview.hero_images_label", "Hero Images"),
            primaryLabel = translationStore.t("creator.overview.designs_generated", "Generated"),
            primaryValue = heroesGenerated,
            secondaryLabel = translationStore.t("creator.overview.products_online", "Online"),
            secondaryValue = heroesOnline,
            onClick = null,
            modifier = Modifier.weight(1f)
        )
    }
}

@Composable
private fun CreatorStatCard(
    icon: String,
    label: String,
    primaryLabel: String,
    primaryValue: String,
    secondaryLabel: String,
    secondaryValue: String,
    onClick: (() -> Unit)?,
    modifier: Modifier = Modifier
) {
    val baseModifier = modifier
        .background(
            color = Color.White.copy(alpha = 0.06f),
            shape = RoundedCornerShape(12.dp)
        )
        .padding(12.dp)
    val clickModifier = if (onClick != null) {
        baseModifier.clickable(
            indication = null,
            interactionSource = remember { MutableInteractionSource() }
        ) { onClick() }
    } else baseModifier
    Column(modifier = clickModifier) {
        Text(
            text = icon,
            style = MaterialTheme.typography.titleMedium,
            modifier = Modifier.padding(bottom = 4.dp)
        )
        Text(
            text = label,
            style = MaterialTheme.typography.labelSmall,
            color = Color.White.copy(alpha = 0.8f)
        )
        Text(
            text = "$primaryLabel: $primaryValue",
            style = MaterialTheme.typography.bodySmall,
            color = Color.White
        )
        Text(
            text = "$secondaryLabel: $secondaryValue",
            style = MaterialTheme.typography.bodySmall,
            color = Color.White.copy(alpha = 0.7f)
        )
    }
}
